#!/usr/bin/env bash
# Exports the mihomo core's embedded version from version.go into the app's Swift source.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VERSION_FILE="$ROOT/Vendor/mihomo/constant/version.go"
OUTPUT="$ROOT/Swihomo/Shared/MihomoCoreVersion.swift"
VERSION="$(awk -F '"' '/^[[:space:]]*Version[[:space:]]*=/ { print $2; exit }' "$VERSION_FILE")"

if [[ -z "$VERSION" ]]; then
    echo "Unable to read mihomo core version from $VERSION_FILE" >&2
    exit 1
fi

printf '%s\n' \
    '// Generated by scripts/export-mihomo-version.sh. Do not edit manually.' \
    'enum MihomoCoreVersion {' \
    "    static let version = \"$VERSION\"" \
    '    static let userAgent = "ClashMeta/\(version)"' \
    '}' > "$OUTPUT"
